### ISSUE TITLE
Error: GSettings key last-used-output-preset not found in schema com.github.wwmm.easyeffects

### ISSUE THREAD

**Issue by akiyiwen** [ulville/eepresetselector#18]
I got the following error after upgrading `easyeffects` from `7.1.6` to `7.1.7`. This error will prevent the extension from displaying any input or output presets. They changed key names from `last-used-output-preset` to `last-loaded-output-preset`, and the same is for input. See https://github.com/wwmm/easyeffects/commit/6437bcb531c758ca16ce1fa3ae6ff08f336c5be0.
```
Error: GSettings key last-used-output-preset not found in schema com.github.wwmm.easyeffects
                                              
Stack trace:
  _checkKey@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:779:23
  createCheckedMethod/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:729:30
  getLastPresets@file:///home/remisiki/.local/share/gnome-shell/extensions/eepresetselector@ulville.github.io/extension.js:404:54
  _refreshMenu@file:///home/remisiki/.local/share/gnome-shell/extensions/eepresetselector@ulville.github.io/extension.js:289:50
  _init/<@file:///home/remisiki/.local/share/gnome-shell/extensions/eepresetselector@ulville.github.io/extension.js:73:22
  @resource:///org/gnome/shell/ui/init.js:21:20
```

**Comment by ahydronous** [comment]
@ulville this is a problem again, at least on Gnome 47 + EEpreset 27 + EasyEffects 7.2.3

**Comment by ulville** [comment]
@ahydronous I have the same setup but I can't reproduce the error. Have you followed the instructions from [here](https://github.com/ulville/eepresetselector/tree/master#-important)? Which distro do you use? In case it's NixOS we don't support NixOS. They patch extensions to work on NixOS on their repos. Please take a look at #11
