### ISSUE TITLE
"Error" when updating to GNOME 42 version

### ISSUE THREAD

**Issue by gqcdm** [ulville/eepresetselector#5]
![image](https://user-images.githubusercontent.com/78142321/162553912-2f9b9dda-e876-4ffb-ad7e-26bda33ed171.png)
![image](https://user-images.githubusercontent.com/78142321/162553929-260ca3df-ae8f-434e-acd8-574b5f6dcdb0.png)

**Comment by ulville** [comment]
Is it still errorring after you log out and log back in

**Comment by gqcdm** [comment]
> Is it still errorring after you log out and log back in

There you go! It's my problem.

**Comment by ulville** [comment]
> > Is it still errorring after you log out and log back in
> 
> There you go! It's my problem.

Sorry I couldn't really understand what you meant here. Is it fixed now or is it still giving an error?
