### ISSUE TITLE
Show current selected preset

### ISSUE THREAD

**Issue by ghost** [ulville/eepresetselector#6]
Currently the extension doesnt show which preset is selected.

**Comment by ulville** [comment]
Hi, thanks for the feedback

I thought about this before but I've been using easyeffects' command-line interface to interact with EasyEffects so far. But it doesn't support an option to give the current selected preset. I could use the extension itself and store the last selected value but this time there is no way to know if the user has changed the preset from inside the EasyEffects app. So I didn't implemented it.

I thought there was no way to implement this. But now I realize EasyEffects app shows the current selected Preset name at the down below in the preset selection menu of itself. So now I think there should be a way to get that. I dont't yet to know how. Maybe dconf or something. A further investigation is needed but I will work on this for the next release along with some other small cosmetic improvements

**Comment by ghost** [comment]
very nice. thank u so much
